import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Worksheet } from '../types';

export const generateStudentWorksheetPDF = async (worksheet: Worksheet) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Header Section
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Singapore Math Worksheet', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 20;

  // Worksheet details in a nice layout
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  
  // Create a box for worksheet info
  pdf.rect(margin, yPosition - 5, pageWidth - (margin * 2), 25);
  yPosition += 5;
  
  pdf.text(`Level: ${worksheet.level}`, margin + 5, yPosition);
  pdf.text(`Topic: ${worksheet.topic}`, margin + 80, yPosition);
  pdf.text(`Difficulty: ${worksheet.difficulty}`, margin + 140, yPosition);
  yPosition += 10;
  
  pdf.text(`Date: ${new Date().toLocaleDateString()}`, margin + 5, yPosition);
  yPosition += 20;

  // Student name field
  pdf.setFont('helvetica', 'bold');
  pdf.text('Student Name: ', margin, yPosition);
  pdf.setFont('helvetica', 'normal');
  
  // Draw a line for student name
  const nameLineStart = margin + 35;
  const nameLineEnd = pageWidth - margin;
  pdf.line(nameLineStart, yPosition + 2, nameLineEnd, yPosition + 2);
  yPosition += 25;

  // Instructions
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'italic');
  pdf.text('Instructions: Show all your working clearly. Write your final answer in the space provided.', margin, yPosition);
  yPosition += 20;

  // Questions Section
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Questions:', margin, yPosition);
  yPosition += 15;

  // Questions with proper spacing
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  
  worksheet.questions.forEach((question, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 80) {
      pdf.addPage();
      yPosition = margin;
    }

    // Question number and text
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${index + 1}.`, margin, yPosition);
    pdf.setFont('helvetica', 'normal');
    
    // Split long questions into multiple lines
    const questionText = question.question;
    const maxWidth = pageWidth - margin - 30;
    const lines = pdf.splitTextToSize(questionText, maxWidth);
    
    lines.forEach((line: string, lineIndex: number) => {
      pdf.text(line, margin + 15, yPosition + (lineIndex * 6));
    });
    
    yPosition += (lines.length * 6) + 5;

    // Working space box
    pdf.setDrawColor(200, 200, 200);
    pdf.rect(margin + 15, yPosition, pageWidth - margin - 35, 25);
    
    // "Working:" label
    pdf.setFontSize(9);
    pdf.setTextColor(128, 128, 128);
    pdf.text('Working:', margin + 20, yPosition + 8);
    
    yPosition += 30;

    // Answer line
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Answer: ', margin + 15, yPosition);
    
    // Draw answer line
    const answerLineStart = margin + 45;
    const answerLineEnd = pageWidth - margin - 20;
    pdf.line(answerLineStart, yPosition + 2, answerLineEnd, yPosition + 2);
    
    yPosition += 20;
    
    // Reset colors and fonts
    pdf.setDrawColor(0, 0, 0);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont('helvetica', 'normal');
  });

  // Footer
  const footerY = pageHeight - 15;
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by Singapore Math Worksheet Generator', pageWidth / 2, footerY, { align: 'center' });

  return pdf;
};

export const generatePDF = async (worksheet: Worksheet, includeAnswers: boolean = false) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Singapore Math Worksheet', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Worksheet details
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Level: ${worksheet.level}`, margin, yPosition);
  pdf.text(`Topic: ${worksheet.topic}`, margin + 60, yPosition);
  pdf.text(`Difficulty: ${worksheet.difficulty}`, margin + 120, yPosition);
  yPosition += 20;

  // Questions
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Questions:', margin, yPosition);
  yPosition += 15;

  pdf.setFont('helvetica', 'normal');
  worksheet.questions.forEach((question, index) => {
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = margin;
    }

    pdf.text(`${index + 1}. ${question.question}`, margin, yPosition);
    yPosition += 15;

    if (includeAnswers) {
      pdf.setFont('helvetica', 'italic');
      pdf.text(`Answer: ${question.answer}`, margin + 10, yPosition);
      yPosition += 10;
      
      if (question.workingSteps && question.workingSteps.length > 0) {
        pdf.text('Working:', margin + 10, yPosition);
        yPosition += 8;
        question.workingSteps.forEach(step => {
          pdf.text(`• ${step}`, margin + 20, yPosition);
          yPosition += 8;
        });
      }
      pdf.setFont('helvetica', 'normal');
      yPosition += 5;
    } else {
      yPosition += 10;
    }
  });

  // Footer
  const footerY = pdf.internal.pageSize.getHeight() - 20;
  pdf.setFontSize(10);
  pdf.text('Generated by Singapore Math Worksheet Generator', pageWidth / 2, footerY, { align: 'center' });

  return pdf;
};

export const downloadWorksheet = async (worksheet: Worksheet, includeAnswers: boolean = false) => {
  let pdf;
  let filename;
  
  if (includeAnswers) {
    // Use the existing function for teacher version with answers
    pdf = await generatePDF(worksheet, true);
    filename = `${worksheet.level}_${worksheet.topic}_${worksheet.difficulty}_with_answers.pdf`;
  } else {
    // Use the new student worksheet function
    pdf = await generateStudentWorksheetPDF(worksheet);
    filename = `${worksheet.level}_${worksheet.topic}_${worksheet.difficulty}_student_worksheet.pdf`;
  }
  
  pdf.save(filename);
};
